# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'table.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.
import sys

from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QApplication, QWidget
from PyQt5.QtGui import QPen,QBrush,QColor

from PyQt5.QtCore import Qt

import sqlite3 as sq

class Ui_Form(object):
    def __init__(self):
        super().__init__()
        self.db_name = '3tour.db'
        self.rectangles = {}
        self.table = ['ID', 'X1', 'X2', 'Y1', 'Y2']
    
    def create(self):
        try:
            with sq.connect(self.db_name) as con:
                cur = con.cursor()
                cur.execute("""
                    CREATE TABLE IF NOT EXISTS RECTANGLES(
                                ID INTEGER PRIMARY KEY AUTOINCREMENT,
                                X1 REAL,
                                X2 REAL,
                                Y1 REAL,
                                Y2 REAL
                                )
                """)
                con.commit()
        except Exception as e:
            print(f'Ошибка БД {e}')

    def load(self):
        try:
            with sq.connect(self.db_name) as con:
                cur = con.cursor()
                cur.execute("""
                    SELECT * FROM RECTANGLES
                """)
                lines = cur.fetchall()
                for line  in enumerate(lines):
                    self.rectangles[line[0]] = line[1]
        except Exception as e:
            print(f'Ошибка БД {e}')
    def add_item(self, id, x1, y1, x2, y2):
        try:
            with sq.connect(self.db_name) as con:
                cur = con.cursor()
                cur.execute("""
                    INSERT OR IGNORE INTO RECTANGLES VALUES (?, ?, ?, ?, ?)
                """, (id, x1, x2, y1, y2))
                con.commit()
        except Exception as e:
            print(f'Ошибка БД {e}')
    
    def delete(self, id):
        try:
            with sq.connect(self.db_name) as con:
                cur = con.cursor()
                cur.execute("""
                    DELETE FROM RECTANGLES WHERE ID = ?
                """, (id,))
        except Exception as e:
            print(f'Ошибка БД {e}')

    def update(self, id, x1=None, x2=None, y1=None, y2=None):
        try:
            with sq.connect(self.db_name) as con:
                cur = con.cursor()
                
                updates = []
                params = []
                
                if x1 is not None:
                    updates.append("X1 = ?")
                    params.append(x1)
                if x2 is not None:
                    updates.append("X2 = ?")
                    params.append(x2)
                if y1 is not None:
                    updates.append("Y1 = ?")
                    params.append(y1)
                if y2 is not None:
                    updates.append("Y2 = ?")
                    params.append(y2)
                
                if not updates:
                    print("Нет данных для обновления")
                    return
                query = f"UPDATE RECTANGLES SET {', '.join(updates)} WHERE ID = ?"
                params.append(id)
                
                cur.execute(query, params)
                con.commit()
        except Exception as e:
            print(f'Ошибка БД при обновлении: {e}')
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(884, 326)
        self.tableWidget = QtWidgets.QTableWidget(Form)
        self.tableWidget.setGeometry(QtCore.QRect(170, 70, 331, 191))
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(5)
        self.tableWidget.setRowCount(3)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(0, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(0, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(0, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(1, 0, item)
        self.graphicsView = QtWidgets.QGraphicsView(Form)
        self.graphicsView.setGeometry(QtCore.QRect(570, 1, 400, 400))
        self.graphicsView.setObjectName("graphicsView")
        self.scene = QtWidgets.QGraphicsScene(self.graphicsView)
        # self.scene.setSceneRect(QtCore.QRectF(0,0,500, 500))
        self.graphicsView.setScene(self.scene)
        pen=QPen(Qt.red,2)
        pen1=QPen(Qt.green,5)
        zal = QColor.fromRgb(255,255,255,150)
        self.scene.addEllipse(1.0, 1.0, 100.0,100.0,pen,zal)
        self.scene.addLine(1,1,500,500,pen1)
        self.scene.addRect(1.0, 1.0, 160.0,170.0,pen)
        self.scene.addText('234wr5etyr6t',)
 
        self.graphicsView.fitInView(self.scene.itemsBoundingRect(), Qt.AspectRatioMode.KeepAspectRatioByExpanding)
        self.tableWidget.cellChanged.connect(self.functions)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        item = self.tableWidget.verticalHeaderItem(0)
        item.setText(_translate("Form", "Новая строка"))
        item = self.tableWidget.verticalHeaderItem(1)
        item.setText(_translate("Form", "Новая строка"))
        item = self.tableWidget.verticalHeaderItem(2)
        item.setText(_translate("Form", "Новая строка"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("Form", "ID"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("Form", "X1"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("Form", "Y1"))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("Form", "X2"))
        item = self.tableWidget.horizontalHeaderItem(4)
        item.setText(_translate("Form", "Y2"))
        __sortingEnabled = self.tableWidget.isSortingEnabled()
        self.tableWidget.setSortingEnabled(False)
        item = self.tableWidget.item(0, 0)
        item.setText(_translate("Form", "00"))
        item = self.tableWidget.item(0, 1)
        item.setText(_translate("Form", "01"))
        item = self.tableWidget.item(0, 2)
        item.setText(_translate("Form", "02"))
        item = self.tableWidget.item(1, 0)
        item.setText(_translate("Form", "10"))
        self.tableWidget.setSortingEnabled(__sortingEnabled)

    # def get_id(self, row):
    #     return self.tableWidget.

    # def update_table(self, row, collum):   
    def functions(self, *args):
        print(args)
        # self.tableWidget.cellChanged.connect(self.update_table)
class MainWindow(QtWidgets.QWidget):
    def __init__(self):
        super().__init__()

        self.ui =Ui_Form()
        self.ui.setupUi(self)


# main = Ui_Form()
# main.create()
# main.load()
# main.setupUi()
app = QApplication(sys.argv)
w =MainWindow()
w.ui.create()
w.ui.load()
# w.ui.functions()
w.show()
# main.functions()
app.exec_()
