# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'table.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.
import sys

from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QApplication, QWidget
from PyQt5.QtGui import QPen,QBrush,QColor

from PyQt5.QtCore import Qt


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(884, 326)
        self.tableWidget = QtWidgets.QTableWidget(Form)
        self.tableWidget.setGeometry(QtCore.QRect(170, 70, 331, 191))
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(3)
        self.tableWidget.setRowCount(3)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(0, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(0, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(0, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(1, 0, item)
        self.graphicsView = QtWidgets.QGraphicsView(Form)
        self.graphicsView.setGeometry(QtCore.QRect(570, 1, 400, 400))
        self.graphicsView.setObjectName("graphicsView")
        self.scene = QtWidgets.QGraphicsScene(self.graphicsView)
        # self.scene.setSceneRect(QtCore.QRectF(0,0,500, 500))
        self.graphicsView.setScene(self.scene)
        pen=QPen(Qt.red,2)
        pen1=QPen(Qt.green,5)
        zal =         QColor.fromRgb(255,255,255,150)
        self.scene.addEllipse(1.0, 1.0, 100.0,100.0,pen,zal)
        self.scene.addLine(1,1,500,500,pen1)
        self.scene.addRect(1.0, 1.0, 160.0,170.0,pen)
        self.scene.addText('234wr5etyr6t',)
 
        self.graphicsView.fitInView(self.scene.itemsBoundingRect(), Qt.AspectRatioMode.KeepAspectRatioByExpanding)


        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        item = self.tableWidget.verticalHeaderItem(0)
        item.setText(_translate("Form", "Новая строка"))
        item = self.tableWidget.verticalHeaderItem(1)
        item.setText(_translate("Form", "Новая строка"))
        item = self.tableWidget.verticalHeaderItem(2)
        item.setText(_translate("Form", "Новая строка"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("Form", "Новый столбец"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("Form", "Новый столбец"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("Form", "Новый столбец"))
        __sortingEnabled = self.tableWidget.isSortingEnabled()
        self.tableWidget.setSortingEnabled(False)
        item = self.tableWidget.item(0, 0)
        item.setText(_translate("Form", "00"))
        item = self.tableWidget.item(0, 1)
        item.setText(_translate("Form", "01"))
        item = self.tableWidget.item(0, 2)
        item.setText(_translate("Form", "02"))
        item = self.tableWidget.item(1, 0)
        item.setText(_translate("Form", "10"))
        self.tableWidget.setSortingEnabled(__sortingEnabled)

class MainWindow(QtWidgets.QWidget):
    def __init__(self):
        super().__init__()
        self.ui =Ui_Form()
        self.ui.setupUi(self)




app = QApplication(sys.argv)
w =MainWindow()
w.show()
app.exec_()
